version: '3.6'
services:
  parser_bot:
    restart: always
    build: .
    container_name: "parser_bot"
    command: sh -c "python3 main.py"
    environment:
      TOKEN: 
      my_chat:
    volumes:
      - /var/log/parser_bot:/logs:rw
